version: '3.8'
services:
  bot:
    image: ptrlrd/kernel:latest
    build: .
    container_name: Kernel
    env_file:
      - .env
    restart: always
    volumes:
#      - sqlite_data:/usr/src/app/data
      - ./data/:/usr/src/app/data   # New volume for bot data

#volumes:
#  sqlite_data:
